package ghost;


import ghost.MenuRegistro;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alejandro
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Menu");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_cerrarsesion = new javax.swing.JButton();
        button_salir = new javax.swing.JButton();
        button_jugar = new javax.swing.JButton();
        button_config = new javax.swing.JButton();
        button_reportes = new javax.swing.JButton();
        button_perfil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        button_cerrarsesion.setText("Cerrar sesion");
        button_cerrarsesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_cerrarsesionMousePressed(evt);
            }
        });
        button_cerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cerrarsesionActionPerformed(evt);
            }
        });

        button_salir.setText("Salir");
        button_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_salirMousePressed(evt);
            }
        });
        button_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_salirActionPerformed(evt);
            }
        });

        button_jugar.setText("Jugar");
        button_jugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_jugarMousePressed(evt);
            }
        });
        button_jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_jugarActionPerformed(evt);
            }
        });

        button_config.setText("Configuracion");
        button_config.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_configMousePressed(evt);
            }
        });
        button_config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_configActionPerformed(evt);
            }
        });

        button_reportes.setText("Reportes");
        button_reportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_reportesMousePressed(evt);
            }
        });
        button_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_reportesActionPerformed(evt);
            }
        });

        button_perfil.setText("Perfil");
        button_perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_perfilMousePressed(evt);
            }
        });
        button_perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_perfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_config, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_jugar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_cerrarsesion, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(button_jugar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_config, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_cerrarsesion, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_cerrarsesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_cerrarsesionMousePressed
        // TODO add your handling code here:
        MenuRegistro mr = new MenuRegistro();
        mr.setVisible(true);
        dispose();
    }//GEN-LAST:event_button_cerrarsesionMousePressed

    private void button_cerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cerrarsesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_cerrarsesionActionPerformed

    private void button_salirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_salirMousePressed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_button_salirMousePressed

    private void button_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_salirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_salirActionPerformed

    private void button_jugarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_jugarMousePressed
        // TODO add your handling code here:
        IngresarJuego ij = new IngresarJuego();
        ij.setVisible(true);
        dispose();
    }//GEN-LAST:event_button_jugarMousePressed

    private void button_jugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_jugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_jugarActionPerformed

    private void button_configMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_configMousePressed
        // TODO add your handling code here:
        Configuracion config = new Configuracion();
        config.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_button_configMousePressed

    private void button_configActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_configActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_configActionPerformed

    private void button_reportesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_reportesMousePressed
        Reportes rep = new Reportes();
        rep.setVisible(true);
        dispose();
    }//GEN-LAST:event_button_reportesMousePressed

    private void button_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_reportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_reportesActionPerformed

    private void button_perfilMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_perfilMousePressed
        Perfil perfil = new Perfil();
        perfil.setVisible(true);
        dispose();
    }//GEN-LAST:event_button_perfilMousePressed

    private void button_perfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_perfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_perfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_cerrarsesion;
    private javax.swing.JButton button_config;
    private javax.swing.JButton button_jugar;
    private javax.swing.JButton button_perfil;
    private javax.swing.JButton button_reportes;
    private javax.swing.JButton button_salir;
    // End of variables declaration//GEN-END:variables
}
